github: blefnk
patreon: blefnk
custom:
  [
    "https://donatello.to/blefnk",
    "https://dono.com.ua/u/nazar",
    "https://buymeacoffee.com/blefnk",
    "https://ko-fi.com/blefnk",
    "https://paypal.me/blefony",
  ]
