# github: blefnk
custom:
  [
    "https://patreon.com/blefnk",
    "https://buymeacoffee.com/blefnk",
    "https://ko-fi.com/blefnk",
    "https://paypal.me/blefony",
    "https://donatello.to/blefnk",
  ]
